-
  In order to test to delete process on sale order.
-
  I try to delete In progress order and check Error Message.
-
  !python {model: sale.order}: |
    try:
        self.unlink(cr, uid, [ref("order7")])
    except Exception,e:
        pass
-
  I delete draft order.
-
  !python {model: sale.order}: |
    context.update({'active_id':ref('order')})
    id = self.copy(cr, uid, ref('order'), context)
    try:
      self.unlink(cr, uid, [id])
    except:
      pass
-
  I delete cancelled order.
-
  !python {model: sale.order}: |
    id = self.copy(cr, uid, ref('order5'), context)
    self.action_cancel(cr, uid, [id])
    try:
      self.unlink(cr, uid, [id])
    except Exception,e:
      pass
